name = "Hextest"
author = "walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75178bef245dc7ecd313ca098b399d6cbb806a3dc4ca4d3feb80a965971473c2"

[versions]
minecraft = "1.20.1"
quilt = "0.23.1"
