name = "Hextest"
author = "walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c379d1187cfe5a48b6aa2895b522b8077a311b667aaf17c97f7b71c90913b6ca"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
