name = "Hextest"
author = "walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "54251e9dc75ffe74125cfe5df916b9cc1a067aa094af5b5086914aefaffde6f4"

[versions]
minecraft = "1.20.1"
quilt = "0.23.1"
