name = "Hextest"
author = "walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3acabc83433adc00625ae332cb716c6ea79db55bee862aba8e8d9e5b93ccf887"

[versions]
minecraft = "1.20.1"
quilt = "0.23.1"
