name = "Hextest"
author = "walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf3392ae1b847a39bae3ffc19730d35cb1a0d8f9d5bdc2641915da376b843dde"

[versions]
minecraft = "1.20.1"
quilt = "0.23.1"
