name = "Hextest"
author = "walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "22f7df2be758bfbf88d8bcf4398c13b56cc43dd12cb5c4ec458cf51fb0a4f149"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
