name = "Hextest"
author = "walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3167d7a09cae6d87396083d18ac337e7376bb863f076222f51258b45eb3e2dcd"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
