name = "Hextest"
author = "walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db681abcbbda23ba47cb06d07dd3ee4f4791fa8ddf480602810c52ac16bca899"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
