name = "Hextest"
author = "walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ef891d7c587f63acba6f08a6df25763fbb6944bb8dcbdc1d77b775e24f3c2a7"

[versions]
minecraft = "1.20.1"
quilt = "0.23.1"
