name = "Hextest"
author = "walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71dc555ba6c32785d6029a4cc9e8ae3f73dd3ffe168dcb52ef189ca9f3e92cd0"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
