name = "Hextest"
author = "walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "82b894ea8995b9062bb137fc8355e142767fad629c10c4b1cd0756623d3f6586"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
