name = "Hextest"
author = "walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7380e64c791bcd20b65b98d870c95b2eb79441b90747c6eab3ff26747fc09cbe"

[versions]
minecraft = "1.20.1"
quilt = "0.23.1"
