name = "Hextest"
author = "walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "85f663599a62e223a73eb462f69cc3a8abd8b0dd85e98193077c8ba54ddd51b5"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
