name = "Hextest"
author = "walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c995f705c019dde3c893355c136cbe87219276d02cef2b3303b76c02c6ad35ee"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
