name = "Hextest"
author = "walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "46670b3a777bb3fb0aab25b531c1b892da9a90a46c53bde93cba3e55b44ce9d1"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
