name = "Hextest"
author = "walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6909cae870e3530f60c5ca74ac154116c7f5c366456fb5e52f76658b672b587f"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
