name = "Hextest"
author = "walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d4db0c0ea5cb01a6843171c8d54c7e765dce3fb749ca4ba61c39d1e41dc1c2ea"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
