name = "Hextest"
author = "walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "58c4549635715e6da234e287867a342173ffc63c8c5df8f8be043a17812ec8c7"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
