name = "Hextest"
author = "walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50ca9c7cc49a1c59ad4530cc8df7192943bce765b36436c8fac60d78210f5086"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
