name = "Hextest"
author = "walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d941d67a78cdc9ff18622fc30042f1492df25bca424f5fa98193b1c2fb387c5e"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
