name = "Hextest"
author = "walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "200d10f824aff46351ef4d7e3d187d95b3b72afb1e940c801fd95ac0de0f9127"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
