name = "Hextest"
author = "walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "55420196e142809941b7118a08a805ec4b026feb59804a03d2739bd2ad72e909"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
