name = "Hextest"
author = "walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "429c4605921eb8a1d498ee9e3877d75c4c5547a1157a2553ce59ca3450807b9f"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
