name = "Hextest"
author = "walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e0e49d437e24c3c4d4574e2a4edee7d4d1c499200862969f664ffb0312ffc93"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
