name = "Hextest"
author = "walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a2069101ef2549535539c6d1ff56fc72426e98d272ee7098efe94b073b77411"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
