name = "Hextest"
author = "walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a9d979a4cafba496c6767141914fecc6d2a08635f15477511de346ec43e41b01"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
