name = "Hextest"
author = "walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "21d98f189a61b2d2582026857040f3b519105ed6687c629203502edc25d266db"

[versions]
minecraft = "1.20.1"
quilt = "0.23.1"
