name = "Hextest"
author = "walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8efbd11d509d8b0c71f4f42c5c833ad31d999799c6cf5127916157bbec998e4c"

[versions]
minecraft = "1.20.1"
quilt = "0.23.1"
