name = "Hextest"
author = "walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be0bdf49efd3416e2c5ed7a1018611ee027794ce60f30a0510c37341f4722821"

[versions]
minecraft = "1.20.1"
quilt = "0.23.1"
