name = "Hextest"
author = "walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41f30071bc52156e1b01615f7505fd12d8dc16cdd4876141649ebc6a64a34f41"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
