name = "Hextest"
author = "walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "46e7f623ce5ce2d26a616667e3e75d3540418bff7cfd77c6befac9d20730dab9"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
