name = "Hextest"
author = "walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d5746db7b9e364d452179676da0bc71fecfa96afc5ee53c200bdecafea8a589"

[versions]
minecraft = "1.20.1"
quilt = "0.23.1"
