name = "Hextest"
author = "walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "31d9f3c1075950390d6b151e71ad8c5531508869e379ba3f754103edefed5e0b"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
