name = "Hextest"
author = "walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50d46644572f4ac00a3280cb9ccbb49c6b22f7289d018b4ad136c879ab382009"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
