name = "Hextest"
author = "walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ae749acb125598490599e098a3000657d6c04167465c7fcaf1623144aaa765ee"

[versions]
minecraft = "1.20.1"
quilt = "0.23.1"
