name = "Hextest"
author = "walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2365bd16024892e63a43bf3975a48842dec5281b7d1b3886f5e58e8a82aa2af3"

[versions]
minecraft = "1.20.1"
quilt = "0.23.1"
