name = "Hextest"
author = "walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b95710ffd0c05ab36fbc53542af48b0ab37675de3e768d8fc0627f93592df68"

[versions]
minecraft = "1.20.1"
quilt = "0.23.1"
