name = "Hextest"
author = "walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "934916b1153cca793144b7aab0357cb172870e4adcbda2422b3580920222ce44"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
